### ISSUE TITLE
Colocar a tag de compatibilidade com o IE em todas as páginas

### ISSUE THREAD

**Issue by fabriciofx** [rpalbq/DSW1#1]
@rpalbq Adicionar a tag de compatibilidade com o IE em todas as páginas:

`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by rpalbq** [comment]
@fabriciofx Verificar correção, por favor 🙂

**Comment by fabriciofx** [comment]
@rpalbq Ok!
